### ISSUE TITLE
Feature request: efun for query_port_number

### ISSUE THREAD

**Issue by bithir** [cotillion/cd-gamedriver#2]
Not an issue - but it would be nice to have query_port_number (from comm1.c) as an efun.

**Comment by bithir** [comment]
I've added it to my driver - I'll see if I can figure out github so I can contribute it back.

Edit: Figured it out

**Comment by cotillion** [comment]
Resolved through #3.

I renamed the efun to int query_remote_port(void|object)
It also uses the same permission check callback as query_ip_number and query_ip_name

Thanks for your contribution!
