### ISSUE TITLE
write_socket_gmcp Denial of Service?

### ISSUE THREAD

**Issue by mindware** [cotillion/cd-gamedriver#5]
I've noticed that executing the efun write_socket_gmcp(str1, str2); leads to a server crash. While I'm still getting familiar with GMCP, just the execution of the following is enough to trrigger the DoS:

`exec write_socket_gmcp("test", "test");`

Results in an immediate crash.  The syslog notes the following:
```
Bad stack after evaluation. Was 37, expected 18446744073708813182, frame ends at 38.
Instruction 263, num arg 0 
Current object was d/Domainname/username/exec_obj
Aborted (core dumped)
Exit status:  134
```

**Comment by cotillion** [comment]
Thanks! Fixed now.

**Comment by mindware** [comment]
This is essentially fixed, however, when I run the above code, I don't see anything sent to the client. I've done packet sniffing on the client side to see if anything reaches the client, and it does not. 

Any example of how one might use write_socket_gmcp effectively? @cotillion

**Comment by cotillion** [comment]
For anything to be sent the client needs to have negotiated GMCP support.
Both CMUD and Mudlet should be doing that however...

**Comment by mindware** [comment]
I tested it in CMUD, and saw no packets. I'll try Mudlet next.

**Comment by mindware** [comment]
I just want to note that I didn't see any traffic. @cotillion
