### ISSUE TITLE
write_socket_gmcp doesn't send anything?

### ISSUE THREAD

**Issue by xxx** [cotillion/cd-gamedriver#6]
Hi,

I'm looking to add GMCP to my game, but nothing seems to be sent. I'm using Mudlet 3.21.0 as my client, and I do see
```
Server sent telnet IAC WILL GMCP (201)
WE send telnet IAC DO GMCP (201)
GMCP enabled
```
when connecting, so it seems like it should work, but any attempt to send 
seems to do nothing. I'm using it like `write_socket_gmcp("Char.Vitals.hp", 6666);`. Am I doing it wrong? This call is valid (i.e. compiles and executes), but nothing is showing up in wireshark. I see this same behavior whether I use `exec` or do the write from an add_action.

Am I missing a piece of the puzzle here? I'm running the driver on the most recent Ubuntu LTS.

@mindware mentioned this behavior as well, in #5

**Comment by cotillion** [comment]
write_socket and write_socket_gmcp operate on this_object().
They're not like write() which writes to the current player.

So what you probably need to do is add a function to /std/player (or your version of the player object) which calls write_socket_gmcp.

This is the version from Genesis:
```
/*
 * Function Name: catch_gmcp
 * Description  : All out of band GMCP messages are sent through here.
 * Arguments    : string package - Message identifier
 *                mixed data     - The message data (val2json rules apply)
 */
nomask public void
catch_gmcp(string package, mixed data)
{
    write_socket_gmcp(package, data);
}
```

**Comment by xxx** [comment]
Thanks for getting back to me so quickly. One more question - Is passing a number not intended? I'm doing `exec find_player("foobar")->catch_gmcp("Char.Vitals.maxhp", 666);`, but the value on the mudlet side is a function, that does nothing when called -
```
lua display(gmcp)
{
  Char = {
    Vitals = {
      mana = 4444,
      hp = "function: 0x6859340",
      maxhp = "6575"
    }
  }
}
```

If I pass integers as values in mappings, or as array members, they show up as integers in mudlet like I expected.

This same behavior happens with floats as well. I'm honestly not sure if this is a driver or mudlet problem.
