### ISSUE TITLE
[Question] Adding ANSI color support

### ISSUE THREAD

**Issue by xxx** [cotillion/cd-gamedriver#7]
Hi,

This is not an issue, just a question. If there's a better place to ask, let me know and I'm happy to do so.

I'm looking to add support for ANSI colors to the driver, but I want to make sure I'm aware of all the places that need to be changed. So far, it looks like I need to update `strlen`, `break_string`, and `write_socket`. Is there any place I'm missing here?

**Comment by cotillion** [comment]
I think that's a good start.
You might want to look at read_file / read_bytes if you want those to be able to read ansi...

**Comment by mindware** [comment]
I managed to upgrade this driver back in 2017 to have ansi color, although I wasn't able to get sprintf to work properly. Would there be any interest if we contribute upstream as a feature?
